<h2 style="color:green" align="center">Machine Learning With Python: Save And Load Trained Model</h2>

In [23]:
import pandas as pd
import numpy as np
import pickle
import joblib
import warnings
warnings.filterwarnings('ignore')

from sklearn import linear_model

%matplotlib inline

In [2]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [6]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [7]:
model.coef_

array([135.78767123])

In [10]:
model.intercept_

180616.43835616432

**Y = m * X + b (m is coefficient and b is intercept)**

In [11]:
135.78767123 * 5000 + 180616.43835616432

859554.7945061643

In [9]:
model.predict([[5000]])

array([859554.79452055])

<h3 style='color:purple'>Save Model To a File Using Python Pickle</h3>

In [12]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

<h4 style='color:purple'>Load Saved Model</h4>

In [13]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [14]:
mp.coef_

array([135.78767123])

In [15]:
mp.intercept_

180616.43835616432

In [16]:
mp.predict([[5000]])

array([859554.79452055])

<h3 style='color:purple'>Save Trained Model Using joblib</h3>

In [17]:
joblib.dump(model, 'model_joblib')

['model_joblib']

<h4 style='color:purple'>Load Saved Model</h4>

In [18]:
mj = joblib.load('model_joblib')

In [19]:
mj.coef_

array([135.78767123])

In [20]:
mj.intercept_

180616.43835616432

In [21]:
mj.predict([[5000]])

array([859554.79452055])