<h2 style='color:white' align='center'>Naive Bayes Tutorial Part 1: Predicting survival from titanic crash</h2>

In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score



%matplotlib inline

In [24]:
df = pd.read_csv("titanic.csv")
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [25]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [26]:
X = df.drop('Survived',axis='columns')
y = df.Survived

In [27]:
#inputs.Sex = inputs.Sex.map({'male': 1, 'female': 2})

In [28]:
dummies = pd.get_dummies(X.Sex)
dummies.head(3)

female   male
0   False   True
1    True  False
2    True  False

In [29]:
X = pd.concat([X,dummies],axis='columns')
X.head(3)

Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False

**I am dropping male column as well because of dummy variable trap theory. One column is enough to repressent male vs female**

In [30]:
X.drop(['Sex','male'],axis='columns',inplace=True)
X.head(3)

Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True

In [31]:
X.columns[X.isna().any()]

Index(['Age'], dtype='object')

In [32]:
X.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [33]:
X.Age = X.Age.fillna(X.Age.mean())
X.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True
3       1  35.0  53.1000    True
4       3  35.0   8.0500   False

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [35]:
model = GaussianNB()

In [36]:
model.fit(X_train,y_train)

GaussianNB()

In [37]:
model.score(X_test,y_test)

0.7947761194029851

In [38]:
X_test[0:10]

Pclass        Age      Fare  female
723       2  50.000000   13.0000   False
748       1  19.000000   53.1000   False
660       1  50.000000  133.6500   False
513       1  54.000000   59.4000    True
235       3  29.699118    7.5500    True
651       2  18.000000   23.0000    True
192       3  19.000000    7.8542    True
9         2  14.000000   30.0708    True
565       3  24.000000   24.1500   False
249       2  54.000000   26.0000   False

In [39]:
y_test[0:10]

723    0
748    0
660    1
513    1
235    0
651    1
192    1
9      1
565    0
249    0
Name: Survived, dtype: int64

In [40]:
model.predict(X_test[0:10])

array([0, 0, 1, 1, 0, 1, 1, 1, 0, 0], dtype=int64)

In [41]:
model.predict_proba(X_test[:10])

array([[0.91848494, 0.08151506],
       [0.51695402, 0.48304598],
       [0.00464584, 0.99535416],
       [0.03567791, 0.96432209],
       [0.50393475, 0.49606525],
       [0.27065014, 0.72934986],
       [0.46511531, 0.53488469],
       [0.23843176, 0.76156824],
       [0.95840599, 0.04159401],
       [0.90940311, 0.09059689]])

**Calculate the score using cross validation**

In [44]:
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.76      , 0.744     , 0.744     , 0.74193548, 0.74193548])